export const GET_SINGLE_SURVEY_REQUEST = 'GET_SINGLE_SURVEY_REQUEST'
export const GET_SINGLE_SURVEY_SUCCESS = 'GET_SINGLE_SURVEY_SUCCESS'
export const GET_SINGLE_SURVEY_FAIL = 'GET_SINGLE_SURVEY_FAIL'

export const GET_ALL_QUESTION_REQUEST = 'GET_ALL_QUESTION_REQUEST'
export const GET_ALL_QUESTION_SUCCESS = 'GET_ALL_QUESTION_SUCCESS'
export const GET_ALL_QUESTION_FAIL = 'GET_ALL_QUESTION_FAIL'


export const SUBMIT_SURVEY_REQUEST = 'SUBMIT_SURVEY_REQUEST'
export const SUBMIT_SURVEY_SUCCESS = 'SUBMIT_SURVEY_SUCCESS'
export const SUBMIT_SURVEY_FAIL = 'SUBMIT_SURVEY_FAIL'
