export const GET_ALL_QUESTION_REQUEST = 'GET_ALL_QUESTION_REQUEST'
export const GET_ALL_QUESTION_SUCCESS = 'GET_ALL_QUESTION_SUCCESS'
export const GET_ALL_QUESTION_FAIL = 'GET_ALL_QUESTION_FAIL'

export const CREATE_QUESTION_REQUEST = 'CREATE_QUESTION_REQUEST'
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS'
export const CREATE_QUESTION_FAIL = 'CREATE_QUESTION_FAIL'
export const CREATE_QUESTION_RESET = 'CREATE_QUESTION_RESET'


export const DELETE_QUESTION_REQUEST = 'DELETE_QUESTION_REQUEST'
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS'
export const DELETE_QUESTION_FAIL = 'DELETE_QUESTION_FAIL'
export const DELETE_QUESTION_RESET = 'DELETE_QUESTION_RESET'

export const UPDATE_QUESTION_REQUEST = 'UPDATE_QUESTION_REQUEST'
export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS'
export const UPDATE_QUESTION_FAIL = 'UPDATE_QUESTION_FAIL'
export const UPDATE_QUESTION_RESET = 'UPDATE_QUESTION_RESET'

