export const GET_ALL_SURVEY_REQUEST = 'GET_ALL_SURVEY_REQUEST'
export const GET_ALL_SURVEY_SUCCESS = 'GET_ALL_SURVEY_SUCCESS'
export const GET_ALL_SURVEY_FAIL = 'GET_ALL_SURVEY_FAIL'

export const CREATE_SURVEY_REQUEST = 'CREATE_SURVEY_REQUEST'
export const CREATE_SURVEY_SUCCESS = 'CREATE_SURVEY_SUCCESS'
export const CREATE_SURVEY_FAIL = 'CREATE_SURVEY_FAIL'
export const CREATE_SURVEY_RESET = 'CREATE_SURVEY_RESET'

export const DELETE_SURVEY_REQUEST = 'DELETE_SURVEY_REQUEST'
export const DELETE_SURVEY_SUCCESS = 'DELETE_SURVEY_SUCCESS'
export const DELETE_SURVEY_FAIL = 'DELETE_SURVEY_FAIL'
export const DELETE_SURVEY_RESET = 'DELETE_SURVEY_RESET'


export const UPDATE_SURVEY_REQUEST = 'UPDATE_SURVEY_REQUEST'
export const UPDATE_SURVEY_SUCCESS = 'UPDATE_SURVEY_SUCCESS'
export const UPDATE_SURVEY_FAIL = 'UPDATE_SURVEY_FAIL'
export const UPDATE_SURVEY_RESET = 'UPDATE_SURVEY_RESET'

export const SEARCH_SURVEYS_REQUEST = 'SEARCH_SURVEYS_REQUEST'
export const SEARCH_SURVEYS_SUCCESS = 'SEARCH_SURVEYS_SUCCESS'
export const SEARCH_SURVEYS_FAIL = 'SEARCH_SURVEYS_FAIL'
export const SEARCH_SURVEYS_RESET = 'SEARCH_SURVEYS_RESET'

export const GET_SINGLE_SURVEY_REQUEST = 'GET_SINGLE_SURVEY_REQUEST'
export const GET_SINGLE_SURVEY_SUCCESS = 'GET_SINGLE_SURVEY_SUCCESS'
export const GET_SINGLE_SURVEY_FAIL = 'GET_SINGLE_SURVEY_FAIL'


export const GET_SINGLE_SURVEY_PREVIEW_REQUEST = 'GET_SINGLE_SURVEY_PREVIEW_REQUEST'
export const GET_SINGLE_SURVEY_PREVIEW_SUCCESS = 'GET_SINGLE_SURVEY_PREVIEW_SUCCESS'
export const GET_SINGLE_SURVEY_PREVIEW_FAIL = 'GET_SINGLE_SURVEY_PREVIEW_FAIL'

export const SUBMIT_SURVEY_REQUEST = 'SUBMIT_SURVEY_REQUEST'
export const SUBMIT_SURVEY_SUCCESS = 'SUBMIT_SURVEY_SUCCESS'
export const SUBMIT_SURVEY_FAIL = 'SUBMIT_SURVEY_FAIL'
export const SUBMIT_SURVEY_RESET = 'SUBMIT_SURVEY_RESET'

export const SEND_SURVEY_TO_EMAIL_REQUEST = 'SEND_SURVEY_TO_EMAIL_REQUEST'
export const SEND_SURVEY_TO_EMAIL_SUCCESS = 'SEND_SURVEY_TO_EMAIL_SUCCESS'
export const SEND_SURVEY_TO_EMAIL_FAIL = 'SEND_SURVEY_TO_EMAIL_FAIL'
export const SEND_SURVEY_TO_EMAIL_RESET = 'SEND_SURVEY_TO_EMAIL_RESET'