export const GET_ALL_USER_REQUEST = 'GET_ALL_USER_REQUEST'
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS'
export const GET_ALL_USER_FAIL = 'GET_ALL_USER_FAIL'

export const GET_SINGLE_USER_REQUEST = 'GET_SINGLE_USER_REQUEST'
export const GET_SINGLE_USER_SUCCESS = 'GET_SINGLE_USER_SUCCESS'
export const GET_SINGLE_USER_FAIL = 'GET_SINGLE_USER_FAIL'


export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'
export const DELETE_USER_RESET = 'DELETE_USER_RESET'

export const ADD_SURVEY_TO_FAVORITE_REQUEST = 'ADD_SURVEY_TO_FAVORITE_REQUEST'
export const ADD_SURVEY_TO_FAVORITE_SUCCESS = 'ADD_SURVEY_TO_FAVORITE_SUCCESS'
export const ADD_SURVEY_TO_FAVORITE_FAIL = 'ADD_SURVEY_TO_FAVORITE_FAIL'
export const ADD_SURVEY_TO_FAVORITE_RESET = 'ADD_SURVEY_TO_FAVORITE_RESET'

export const REMOVE_SURVEY_FROM_FAVORITE_REQUEST = 'REMOVE_SURVEY_FROM_FAVORITE_REQUEST'
export const REMOVE_SURVEY_FROM_FAVORITE_SUCCESS = 'REMOVE_SURVEY_FROM_FAVORITE_SUCCESS'
export const REMOVE_SURVEY_FROM_FAVORITE_FAIL = 'REMOVE_SURVEY_FROM_FAVORITE_FAIL'
export const REMOVE_SURVEY_FROM_FAVORITE_RESET = 'REMOVE_SURVEY_FROM_FAVORITE_RESET'

export const GET_ALL_FAVORITES_REQUEST = 'GET_ALL_FAVORITES_REQUEST'
export const GET_ALL_FAVORITES_SUCCESS = 'GET_ALL_FAVORITES_SUCCESS'
export const GET_ALL_FAVORITES_FAIL = 'GET_ALL_FAVORITES_FAIL'


export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET'